# Generated by Django 4.1.13 on 2023-11-09 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 10, 23, 59, 867834, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
