# Generated by Django 4.2 on 2023-10-30 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_date_alter_post_img_alter_post_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 10, 30, 9, 32, 30, 367089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
