# Generated by Django 4.2 on 2023-11-08 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(default="", upload_to="images_uploaded"),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 8, 18, 45, 59, 869068, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
