# Generated by Django 4.1.13 on 2023-11-09 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_post_date_alter_post_img_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(default=datetime.date(2023, 11, 9)),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 9, 27, 37, 783142, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
