# Generated by Django 4.1.13 on 2023-11-09 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_date_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 9, 43, 4, 384660, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
