# Generated by Django 4.1.13 on 2023-11-09 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Technology", "Technology"),
                    ("Business", "Business"),
                    ("Web Development", "Web Development"),
                    ("Politics", "Politics"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 9, 59, 16, 713286, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
