# Generated by Django 4.1.13 on 2023-11-09 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_post_category_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 10, 3, 39, 872156, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
