# Generated by Django 4.1.13 on 2023-11-09 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_post_content_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 10, 4, 41, 113204, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
