# Generated by Django 4.1.13 on 2023-11-09 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_content_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 10, 14, 20, 792282, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
