# Generated by Django 4.1.13 on 2023-11-09 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_time"),
        ("blog", "0004_alter_post_time"),
        ("blog", "0013_alter_post_time"),
    ]

    operations = []
