# Generated by Django 4.1.13 on 2023-11-09 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_merge_20231109_1126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 10, 28, 6, 840779, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
