# Generated by Django 4.1.13 on 2023-11-09 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 9, 10, 33, 16, 446392, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
