# Generated by Django 4.1.13 on 2023-11-10 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0025_project_img_alter_post_date_alter_post_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Technology", "Technology"),
                    ("Business", "Business"),
                    ("Web Development", "Web Development"),
                    ("Mobile Development", "Mobile Development"),
                    ("Politics", "Politics"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 10, 7, 46, 36, 533990, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
