# Generated by Django 4.1.13 on 2023-11-11 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0027_alter_post_date_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 11, 11, 8, 33, 22, 807487, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
